### PR TITLE
Convert from Any::Moose to Moo

### LINKED ISSUE #4: Migrate to Moo
since Any::Moose is deprecated

### PR DESCRIPTION
**Pull request by tsibley**
Any::Moose is deprecated, for good reason!

Note that `t/cycle.t` fails on master for me (didn't dig into it) and it continues to fail in this PR for me too.

Closes #4.

### CODE REVIEW

**Comment by clkao** [comment]
@tsible++! It seems that `t/trait.t` is failing trying to require Any::Moose?

**Comment by tsibley** [comment]
Oh, good catch.  It was passing for me, but still using Any::Moose!  I fixed up the commit and repushed.  (Also, adjusted `.travis.yml`.)

**Comment by tsibley** [comment]
Looks like it's passing travis again.

**Comment by tsibley** [comment]
Looks like the cycle tests fail on Travis too, so it's not just my machine or a certain Perl version.  These were known to fail before the change to Moo, though.

**Comment by tsibley** [comment]
\o/

**Pull request merged**
